spring:
    application:
    name: spring-batch
    profiles:
        active: mysql

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password:
            driver-class-name: org.h2.Driver
    batch:
        jdbc:
            initialize-schema: embedded
            table-prefix: SYSTEM_ # 해당 prefix로 batch table을 생성함
        job:
            enabled: false # 자동실행 방지
            names: ${job.name:NONE} #name에 해당하는 job을 실행함, ${job.name} -> job.name에 해당하는 값을 동적으로 처리하기 위해 처리

---
spring:
    config:
        activate:
            on-profile: mysql
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
            username: root
            password: 1234
            driver-class-name: com.mysql.jdbc.Driver
    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: always